### ISSUE TITLE
Return null or leave out the field if the data is not available

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#29]
I was wondering, when certain field numeric value is not available. Instead of returning String

    "EPSSurpriseDollar": "N/A",

Can we have

    "EPSSurpriseDollar": null,

Or

    "EPSSurpriseDollar": -1,

Or, just remove the field completely.

This is because, if we try to convert the returned json string to typed safe Java object

```
class Stats {
    ...
    public double EPSSurpriseDollar;
    ...
}
```

such json string to java object conversion will fail, if "NA" string is possible value.

Thank you.

p/s We are using http://square.github.io/retrofit/ and https://github.com/google/gson.

**Comment by shuwnyuantee** [comment]
@yccheok 👍  I second this too, because code will throw exception if convert from "N/A" to int or double or long.

**Comment by shuwnyuantee** [comment]
@joshuablackburn-iex  May I know any estimate on timeline for this fix? As String "N/A" is causing exception thrown for double, int, long fields. Thanks!

**Comment by joshuablackburn-iex** [comment]
This is being worked on, and we hope to have it rolled out by end of day tomorrow.  I will let you know once we've pushed the fix.

**Comment by shuwnyuantee** [comment]
@joshuablackburn-iex  Cool, thanks a lot for your prompt reply & the fix. 👍

**Comment by joshuablackburn-iex** [comment]
We've standardized the return values to match appropriate data type. For unknown values we use null. Please let me know if you find any data that still returns a value that breaks your typed variables.

**Comment by shuwnyuantee** [comment]
@joshuablackburn-iex 

Thanks for looking into the issue 👍  However I still face some issues. In your response, eg: Key Stats API

```
    "dividendYield": "null",
    "exDividendDate": "null",
    "latestEPS": 2.46,
    "latestEPSDate": "2017-03-31",
    "sharesOutstanding": 2529364189,
    "float": 2529364189,
    "returnOnEquity": 19,
    "consensusEPS": 0.47,
    "numberOfEstimates": 5,
    "EPSSurpriseDollar": null,
```

Sometimes `null` is returned as `String "null"`, which is problematic.

In case of value unavailable, can you always return `null`, not the `String "null"` ? This applies for all field types of String or numbers.

Thanks a lot :)

**Comment by shuwnyuantee** [comment]
@joshuablackburn-iex  Sorry to buzz you again. Any update on this? Can this be fixed as mentioned above?

Thanks a lot for your time! :)

**Comment by yccheok** [comment]
Yes. Looking forward this to be fixed, as `null` and `"null"` are 2 different data types.

**Comment by joshuablackburn-iex** [comment]
Can you please check the data, and let us know if you are seeing what you expect.

**Comment by shuwnyuantee** [comment]
@joshuablackburn-iex 

I checked, `stats` API call is fixed. 

But `financials` API call still have problem. Some number field still return string:  `"totalDebt": "NaN",`

Returning any string like `"NaN"` has same effect as returning `"null"` string, causing same error. Can you fix them? Thanks!

<img width="626" alt="financials" src="https://user-images.githubusercontent.com/614382/31240536-9a80821e-aa33-11e7-9eb4-137aa201429f.png">

**Comment by joshuablackburn-iex** [comment]
I understand the impact of mixed types.  Just trying to track down all the individual data fields.

**Comment by shuwnyuantee** [comment]
@joshuablackburn-iex  👍  Great. Btw I only test a few API though, not sure about the rest yet.

Thanks for tracking down the issue.

**Comment by joshuablackburn-iex** [comment]
The financials should be good to go

**Comment by shuwnyuantee** [comment]
@joshuablackburn-iex  Ok, `financials` works well now, thanks.

**Comment by yccheok** [comment]
Hi, today I realize `NaN` problem appear in stats API (In `revenuePerEmployee`)

https://api.iextrading.com/1.0/stock/market/batch?symbols=XLK&types=quote,stats

Can it be fixed too to `null`?

**Comment by yccheok** [comment]
Here's the screenshot.

![2017-10-26 21_49_10-photos](https://user-images.githubusercontent.com/308276/32056662-d0fcd210-ba97-11e7-9a46-da4962d35433.png)

**Comment by lssilva** [comment]
It would be nice to have a consistent representation of NULL or not available values

**Comment by shuwnyuantee** [comment]
Hi,

I just checked that `stats` api still returning `NaN` for some fields, eg: `revenuePerShare`, `revenuePerEmployee`.

https://api.iextrading.com/1.0/stock/MJ/stats

Can it be fixed to null? Thanks!

<img width="386" alt="aaaaa" src="https://user-images.githubusercontent.com/614382/36832952-b46aaf8a-1d68-11e8-8836-017e0b81b747.png">
